name: mi_app
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icon_craft: ^0.1.0+3  # <--- Mueve aquí esta línea

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo1.png
    - assets/logogoogle.png

  fonts:
    - family: Italiana
      fonts:
        - asset: assets/fonts/Italiana-Regular.ttf
